site_name: Johannes' Kenpo Notes ğŸ¥‹ğŸ—’ï¸
theme:
  name: material
  features:
    - navigation.expand
    - tabs
plugins: 
  - search
  - roamlinks
  - mkdocs-video
  - include_dir_to_nav

nav:
  - index.md
  - Techniques: techniques
  - Easy to Mix Up: easy-to-mix-up
  - Forms: forms
  - Belts: belts
  - Web of Knowledge ğŸ•¸ğŸ’¡: web-of-knowledge
  - Single Techniques: single-techniques