site_name: Johannes' Kenpo Notes ğŸ¥‹ğŸ—’ï¸
theme:
  name: material
  features:
    - navigation.expand
    - tabs
plugins: 
  - search
  - roamlinks
  - mkdocs-video

# nav:
#   - index.md
#   - Belts:
#     - belts/yellow.md
#     - belts/orange.md